### ISSUE TITLE
FR: Add yaml frontmatter protection as well

### ISSUE THREAD

**Issue by chrisgrieser** [Ummler/obsidian-auto-correct-capitals#6]
While this plugin excludes code and math blocks, it should imo exclude writing in the yaml frontmatter (in source mode). For example:

```yaml
---
# typing this
foo: BAr 

# will become
Foo: Bar 
---
```

While it's a nuisance with the values, changing the capitalization of the frontmatter *keys* can make the frontmatter invalid in certain contexts.
